global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:5001']

  - job_name: 'products-service'
    static_configs:
      - targets: ['products-service:5011']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:5012']

  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments-service:5013']

  - job_name: 'notifications-service'
    static_configs:
      - targets: ['notifications-service:5014']

  - job_name: 'users-service'
    static_configs:
      - targets: ['users-service:5015']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:5018']

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend-service:5019'] 