apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: ecommerce-daily-backup
  namespace: velero
spec:
  schedule: "0 1 * * *"
  template:
    hooks: {}
    includedNamespaces:
    - ecommerce
    ttl: 720h
    storageLocation: default
    volumeSnapshotLocations:
    - default
    defaultVolumesToRestic: true
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: azure
  objectStorage:
    bucket: ecommerce-backups
  config:
    resourceGroup: ecommerce-rg
    storageAccount: ecommercebackups
    subscriptionId: $(AZURE_SUBSCRIPTION_ID)
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: azure
  config:
    resourceGroup: ecommerce-rg
    subscriptionId: $(AZURE_SUBSCRIPTION_ID) 