apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  # Application Settings
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80;https://+:443"
  
  # Logging Configuration
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Information"
  Logging__LogLevel__System: "Warning"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
  Logging__LogLevel__Microsoft.EntityFrameworkCore: "Warning"
  
  # CORS Configuration
  Cors__AllowedOrigins: "https://app.ecommerce.com"
  Cors__AllowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
  Cors__AllowedHeaders: "Content-Type,Authorization"
  Cors__AllowCredentials: "true"
  
  # Health Checks
  HealthChecks__Enabled: "true"
  HealthChecks__Endpoint: "/health"
  HealthChecks__UIEnabled: "true"
  HealthChecks__UIEndpoint: "/health-ui"
  
  # Metrics Configuration
  Metrics__Enabled: "true"
  Metrics__Endpoint: "/metrics"
  Metrics__CollectInterval: "00:00:15"
  Metrics__PrometheusEnabled: "true"
  Metrics__PrometheusEndpoint: "/metrics-prometheus"
  
  # Monitoring Configuration
  Monitoring__Enabled: "true"
  Monitoring__AlertManagerUrl: "http://alertmanager.ecommerce.svc.cluster.local:9093"
  Monitoring__GrafanaUrl: "http://grafana.ecommerce.svc.cluster.local:3000"
  
  # Logging Configuration
  Logging__ElasticsearchUrl: "http://elasticsearch.ecommerce.svc.cluster.local:9200"
  Logging__KibanaUrl: "http://kibana.ecommerce.svc.cluster.local:5601"
  Logging__LogstashEnabled: "true"
  Logging__LogstashHost: "logstash.ecommerce.svc.cluster.local"
  Logging__LogstashPort: "5044"
  
  # Backup Configuration
  Backup__Enabled: "true"
  Backup__Schedule: "0 1 * * *"
  Backup__RetentionDays: "30"
  Backup__StorageAccount: "ecommercebackups"
  Backup__StorageContainer: "ecommerce-backups" 