apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-alertmanager-config
  namespace: monitoring
  labels:
    app: order-service
    release: prometheus
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK'
    
    route:
      group_by: ['alertname', 'service']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'order-service-team'
      routes:
      - match:
          severity: critical
        receiver: 'order-service-critical'
        group_wait: 10s
        repeat_interval: 1h
      - match:
          severity: warning
        receiver: 'order-service-warning'
        group_wait: 30s
        repeat_interval: 4h
    
    receivers:
    - name: 'order-service-team'
      slack_configs:
      - channel: '#order-service-alerts'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
    
    - name: 'order-service-critical'
      slack_configs:
      - channel: '#order-service-critical'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
      pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_ROUTING_KEY'
        send_resolved: true
        description: '{{ template "pagerduty.default.description" . }}'
    
    - name: 'order-service-warning'
      slack_configs:
      - channel: '#order-service-warnings'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
    
    templates:
    - '/etc/alertmanager/template/*.tmpl' 