apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce
  labels:
    app: user-service
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
      environment: production
  template:
    metadata:
      labels:
        app: user-service
        environment: production
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: user-service
        image: ecommerce.azurecr.io/user-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        envFrom:
        - configMapRef:
            name: ecommerce-config
        env:
        - name: ConnectionStrings__UserDb
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: connection-string
        - name: AzureAdB2C__Instance
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: azure-ad-b2c-instance
        - name: AzureAdB2C__ClientId
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: azure-ad-b2c-client-id
        - name: AzureAdB2C__Domain
          valueFrom:
            secretKeyRef:
              name: user-secrets
              key: azure-ad-b2c-domain
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: user-service
    environment: production 